version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'master'
    assignees:
      - 'OmerBilgin21'
    ignore:
      - dependency-name: '@types/node'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
