version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'daily'
    target-branch: 'master'
    assignees:
      - 'OmerBilgin21'
  - package-ecosystem: 'github-actions'
    directory: '/backend'
    schedule:
      interval: 'daily'
