# Stage 1: Build
FROM node:22.13.1 AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY src ./src
COPY eslint.config.mjs ./
COPY prettier.config.mjs ./

RUN npm run build

# Stage 2: Runtime
FROM node:22.13.1-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./

RUN npm install --omit=dev --no-audit --no-fund

ENV NODE_ENV=$NODE_ENV
ENV APP_PORT=$APP_PORT
ENV LLM_URL=$LLM_URL
ENV GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
ENV DB_PORT=$DB_PORT
ENV DB_HOST=$DB_HOST
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS

EXPOSE 8000

CMD ["node", "./dist/app.js"]
