# Stage 1: Build
FROM node:22.13.1 AS builder

WORKDIR /app

# Only copy the files needed for dependency install first (for caching)
COPY package*.json ./
COPY tsconfig.json ./

# Install deps
RUN npm install
RUN npx tsc --version

# Copy rest of the app
COPY src ./src
COPY eslint.config.mjs ./
COPY prettier.config.mjs ./

# Run TypeScript compiler
RUN npm run build

# Stage 2: Runtime
FROM node:22.13.1-slim

WORKDIR /app

# Copy only built output and minimal files
COPY --from=builder /app/dist ./dist
COPY package*.json ./

# Only install production deps
RUN npm install --omit=dev --no-audit --no-fund

# Set environment variables
ENV NODE_ENV=$NODE_ENV
ENV APP_PORT=$APP_PORT
ENV LLM_URL=$LLM_URL
ENV GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
ENV DB_PORT=$DB_PORT
ENV DB_HOST=$DB_HOST
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS

EXPOSE 8000

CMD ["node", "./dist/app.js"]
