import { Book, MaturityRating, SuccessfulGoogleResponse } from 'schemas';
export const mockUser = {
  id: 1,
  firstName: 'omer',
  lastName: 'b',
  password: '123',
  email: 'ob@verysecret.com',
};

export const mockFavorite = {
  id: 1,
  selfLink: 'http://mock-book-link.com',
  userId: 1,
};

export const mockDislike = {
  id: 1,
  selfLink: 'http://mock-book-link-2.com',
  userId: 1,
};

export const mockFavoriteCategories = [
  {
    id: 1,
    name: 'fiction',
    rank: 9,
    userId: 1,
  },
  {
    id: 2,
    name: 'poem',
    rank: 1,
    userId: 1,
  },
];

export const mockBooks: Book[] = [
  {
    kind: 'books#volume',
    id: '1',
    etag: 'etag1',
    selfLink: 'http://example.com/book1',
    volumeInfo: {
      title: 'The Adventures of TypeScript',
      authors: ['Jane Doe'],
      publishedDate: '2022',
      industryIdentifiers: [
        { type: 'ISBN_10', identifier: '1234567890' },
        { type: 'ISBN_13', identifier: '123-4567890123' },
      ],
      description: 'An adventurous journey into the world of TypeScript.',
      readingModes: { text: true, image: false },
      pageCount: 320,
      printType: 'BOOK',
      categories: ['Programming', 'Technology'],
      publisher: 'TechBooks Publishing',
    },
    saleInfo: {},
    accessInfo: {},
    searchInfo: {},
    maturityRating: MaturityRating.NOT_MATURE,
    allowAnonLogging: true,
    contentVersion: '1.0.0',
    imageLinks: {
      smallThumbnail: 'http://example.com/smallThumbnail1.jpg',
      thumbnail: 'http://example.com/thumbnail1.jpg',
    },
    language: 'en',
    previewLink: 'http://example.com/preview1',
    infoLink: 'http://example.com/info1',
    canonicalVolumeLink: 'http://example.com/canonical1',
  },
  {
    kind: 'books#volume',
    id: '2',
    etag: 'etag2',
    selfLink: 'http://example.com/book2',
    volumeInfo: {
      title: 'Mastering JavaScript',
      authors: ['John Smith'],
      publishedDate: '2021',
      industryIdentifiers: [
        { type: 'ISBN_10', identifier: '0987654321' },
        { type: 'ISBN_13', identifier: '987-6543210987' },
      ],
      description: 'A comprehensive guide to mastering JavaScript.',
      readingModes: { text: true, image: true },
      pageCount: 450,
      printType: 'BOOK',
      categories: ['Programming', 'JavaScript'],
      publisher: 'Code Masters',
    },
    saleInfo: {},
    accessInfo: {},
    searchInfo: {},
    maturityRating: MaturityRating.NOT_MATURE,
    allowAnonLogging: true,
    contentVersion: '2.1.0',
    imageLinks: {
      smallThumbnail: 'http://example.com/smallThumbnail2.jpg',
      thumbnail: 'http://example.com/thumbnail2.jpg',
    },
    language: 'en',
    previewLink: 'http://example.com/preview2',
    infoLink: 'http://example.com/info2',
    canonicalVolumeLink: 'http://example.com/canonical2',
  },
  {
    kind: 'books#volume',
    id: '3',
    etag: 'etag3',
    selfLink: 'http://example.com/book3',
    volumeInfo: {
      title: 'The Art of Database Design',
      authors: ['Alice Johnson'],
      publishedDate: '2020',
      industryIdentifiers: [
        { type: 'ISBN_10', identifier: '1122334455' },
        { type: 'ISBN_13', identifier: '112-2334455667' },
      ],
      description: 'A deep dive into effective database design practices.',
      readingModes: { text: false, image: true },
      pageCount: 300,
      printType: 'BOOK',
      categories: ['Databases', 'Technology'],
      publisher: 'Data Insights',
    },
    saleInfo: {},
    accessInfo: {},
    searchInfo: {},
    maturityRating: MaturityRating.NOT_MATURE,
    allowAnonLogging: false,
    imageLinks: {
      smallThumbnail: 'http://example.com/smallThumbnail3.jpg',
      thumbnail: 'http://example.com/thumbnail3.jpg',
    },
    language: 'en',
    previewLink: 'http://example.com/preview3',
    infoLink: 'http://example.com/info3',
    canonicalVolumeLink: 'http://example.com/canonical3',
  },
  {
    kind: 'books#volume',
    id: '4',
    etag: 'etag4',
    selfLink: 'http://example.com/book4',
    volumeInfo: {
      title: 'Advanced React Techniques',
      authors: ['Emma Brown'],
      publishedDate: '2023',
      industryIdentifiers: [
        { type: 'ISBN_10', identifier: '6677889900' },
        { type: 'ISBN_13', identifier: '667-7889900112' },
      ],
      description: 'Learn advanced techniques in React development.',
      readingModes: { text: true, image: true },
      pageCount: 400,
      printType: 'BOOK',
      categories: ['Web Development', 'React'],
      publisher: 'WebDev Books',
    },
    saleInfo: {},
    accessInfo: {},
    searchInfo: {},
    maturityRating: MaturityRating.NOT_MATURE,
    allowAnonLogging: true,
    imageLinks: {
      smallThumbnail: 'http://example.com/smallThumbnail4.jpg',
      thumbnail: 'http://example.com/thumbnail4.jpg',
    },
    language: 'en',
    previewLink: 'http://example.com/preview4',
    infoLink: 'http://example.com/info4',
    canonicalVolumeLink: 'http://example.com/canonical4',
  },
  {
    kind: 'books#volume',
    id: '5',
    etag: 'etag5',
    selfLink: 'http://example.com/book5',
    volumeInfo: {
      title: 'Introduction to AI',
      authors: ['Dr. Sarah Lee'],
      publishedDate: '2019',
      industryIdentifiers: [
        { type: 'ISBN_10', identifier: '5566778899' },
        { type: 'ISBN_13', identifier: '556-6778899001' },
      ],
      description: "A beginner's guide to Artificial Intelligence.",
      readingModes: { text: false, image: true },
      pageCount: 220,
      printType: 'BOOK',
      categories: ['Artificial Intelligence', 'Technology'],
      publisher: 'AI Press',
    },
    saleInfo: {},
    accessInfo: {},
    searchInfo: {},
    maturityRating: MaturityRating.MATURE,
    allowAnonLogging: false,
    imageLinks: {
      smallThumbnail: 'http://example.com/smallThumbnail5.jpg',
      thumbnail: 'http://example.com/thumbnail5.jpg',
    },
    language: 'en',
    previewLink: 'http://example.com/preview5',
    infoLink: 'http://example.com/info5',
    canonicalVolumeLink: 'http://example.com/canonical5',
  },
];

export const mockGoogleResponse: SuccessfulGoogleResponse = {
  kind: 'i do not know',
  totalItems: 5,
  items: mockBooks,
};
